"""
Train a simple sequence model to monitor magnetometer data.

This script:
- Loads `airpods_432dd46.csv` generated by `binary_magneto_gen.py`
- Uses x, y, z as a sequence input to predict the binary `target`
- Trains on ALL rows (no train/test split per user's request)
- Saves a small PyTorch model for later live use

Usage (from repo root):
    python -m experimental.train_magneto_monitor \
        --csv-path experimental/airpods_432dd46.csv \
        --seq-len 32 \
        --batch-size 32 \
        --epochs 40
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Tuple

import numpy as np
import pandas as pd
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset


DEFAULT_CSV_NAME = "airpods_432dd46.csv"
THIS_DIR = Path(__file__).resolve().parent


class MagnetoSequenceDataset(Dataset):
    """
    Build sliding-window sequences from the raw CSV.

    - Input:  sequence of shape (seq_len, 3) for x/y/z
    - Target: scalar 0/1 label corresponding to the LAST timestep in the window
    """

    def __init__(self, csv_path: Path, seq_len: int):
        super().__init__()
        self.csv_path = csv_path
        self.seq_len = seq_len

        df = pd.read_csv(csv_path)
        if not {"x", "y", "z", "target"}.issubset(df.columns):
            raise ValueError(
                f"CSV at {csv_path} must contain columns: x, y, z, target; "
                f"found {list(df.columns)}"
            )

        # (N, 3) features and (N,) targets
        feats = df[["x", "y", "z"]].astype("float32").to_numpy()
        targets = df["target"].astype("float32").to_numpy()

        if feats.shape[0] < seq_len:
            raise ValueError(
                f"Not enough rows ({feats.shape[0]}) for seq_len={seq_len}. "
                "Reduce seq_len or record longer runs."
            )

        # Normalize per-feature using dataset statistics for stability.
        self.mean = feats.mean(axis=0, keepdims=True)
        self.std = feats.std(axis=0, keepdims=True)
        # Avoid div-by-zero
        self.std[self.std == 0.0] = 1.0
        feats_norm = (feats - self.mean) / self.std

        # Build sliding windows
        windows = []
        window_targets = []
        for start in range(0, feats_norm.shape[0] - seq_len + 1):
            end = start + seq_len
            windows.append(feats_norm[start:end])
            # Label is the target at the last timestep in the window
            window_targets.append(targets[end - 1])

        self.x = torch.from_numpy(np.stack(windows))  # (num_windows, seq_len, 3)
        self.y = torch.from_numpy(np.stack(window_targets))  # (num_windows,)

    def __len__(self) -> int:
        return self.x.shape[0]

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.x[idx], self.y[idx]


class MagnetoLSTM(nn.Module):
    """
    Small LSTM-based binary classifier over magnetometer sequences.
    """

    def __init__(
        self,
        input_dim: int = 3,
        hidden_dim: int = 32,
        num_layers: int = 1,
        dropout: float = 0.1,
    ):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.head = nn.Sequential(
            nn.LayerNorm(hidden_dim),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: (batch, seq_len, input_dim)
        out, _ = self.lstm(x)
        # Take last timestep
        last = out[:, -1, :]  # (batch, hidden_dim)
        logits = self.head(last).squeeze(-1)  # (batch,)
        return logits


@dataclass
class TrainConfig:
    csv_path: Path
    seq_len: int = 32
    batch_size: int = 32
    epochs: int = 40
    lr: float = 3e-3
    hidden_dim: int = 32
    num_layers: int = 1
    dropout: float = 0.1
    device: str = "cuda" if torch.cuda.is_available() else "cpu"
    out_path: Path = THIS_DIR / "magneto_monitor.pt"


def parse_args() -> TrainConfig:
    parser = argparse.ArgumentParser(description="Train magnetometer monitor model.")
    parser.add_argument(
        "--csv-path",
        type=str,
        default=str(THIS_DIR / DEFAULT_CSV_NAME),
        help="Path to CSV file with columns x,y,z,target.",
    )
    parser.add_argument("--seq-len", type=int, default=32, help="Sequence length.")
    parser.add_argument("--batch-size", type=int, default=32, help="Batch size.")
    parser.add_argument("--epochs", type=int, default=40, help="Training epochs.")
    parser.add_argument(
        "--lr", type=float, default=3e-3, help="Learning rate (Adam)."
    )
    parser.add_argument(
        "--hidden-dim", type=int, default=32, help="LSTM hidden size."
    )
    parser.add_argument(
        "--num-layers", type=int, default=1, help="Number of LSTM layers."
    )
    parser.add_argument(
        "--dropout", type=float, default=0.1, help="LSTM dropout (num_layers>1)."
    )
    parser.add_argument(
        "--out-path",
        type=str,
        default=str(THIS_DIR / "magneto_monitor.pt"),
        help="Where to save the trained model (torch.save).",
    )

    args = parser.parse_args()
    cfg = TrainConfig(
        csv_path=Path(args.csv_path),
        seq_len=args.seq_len,
        batch_size=args.batch_size,
        epochs=args.epochs,
        lr=args.lr,
        hidden_dim=args.hidden_dim,
        num_layers=args.num_layers,
        dropout=args.dropout,
        out_path=Path(args.out_path),
    )
    return cfg


def train(cfg: TrainConfig) -> None:
    print(f"Loading data from {cfg.csv_path} ...")
    dataset = MagnetoSequenceDataset(cfg.csv_path, cfg.seq_len)
    loader = DataLoader(
        dataset, batch_size=cfg.batch_size, shuffle=True, drop_last=False
    )

    device = torch.device(cfg.device)
    model = MagnetoLSTM(
        input_dim=3,
        hidden_dim=cfg.hidden_dim,
        num_layers=cfg.num_layers,
        dropout=cfg.dropout,
    ).to(device)

    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.lr)

    num_batches = len(loader)
    print(
        f"Dataset windows: {len(dataset)} | "
        f"seq_len={cfg.seq_len} | "
        f"device={device}"
    )

    for epoch in range(1, cfg.epochs + 1):
        model.train()
        running_loss = 0.0
        running_correct = 0
        running_total = 0

        for xb, yb in loader:
            xb = xb.to(device)  # (B, T, 3)
            yb = yb.to(device)  # (B,)

            optimizer.zero_grad()
            logits = model(xb)  # (B,)
            loss = criterion(logits, yb)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * xb.size(0)
            with torch.no_grad():
                preds = (torch.sigmoid(logits) > 0.5).float()
                running_correct += (preds == yb).sum().item()
                running_total += yb.numel()

        epoch_loss = running_loss / running_total
        epoch_acc = running_correct / running_total if running_total > 0 else 0.0
        print(
            f"Epoch {epoch:03d}/{cfg.epochs} "
            f"- loss: {epoch_loss:.4f} - acc: {epoch_acc:.4f}"
        )

    # Save model + metadata needed for live use.
    cfg.out_path.parent.mkdir(parents=True, exist_ok=True)
    save_obj = {
        "state_dict": model.state_dict(),
        "seq_len": cfg.seq_len,
        "input_dim": 3,
        "hidden_dim": cfg.hidden_dim,
        "num_layers": cfg.num_layers,
        "dropout": cfg.dropout,
        "feature_mean": dataset.mean.astype("float32"),
        "feature_std": dataset.std.astype("float32"),
    }
    torch.save(save_obj, cfg.out_path)
    print(f"Saved trained model to {cfg.out_path}")


def main() -> None:
    cfg = parse_args()
    train(cfg)


if __name__ == "__main__":
    main()

