[package]
name = "rustcore"
version = "0.1.0"
edition = "2024"

[lib]
name = "rustcore"
crate-type = ["cdylib", "staticlib"]

[dependencies]
burn = { version = "0.19.1", features = ["train"] }
burn-ndarray = "0.19.1"
burn-autodiff = "0.19.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
